# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml README.md main.py .

# Install dependencies
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir .

# Ensure logs appear immediately
ENV PYTHONUNBUFFERED=1

# Start the MCP server
CMD ["python", "main.py"]
